version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
    hostname: server
    command: npm run develop
    ports:
      - "1337:1337"
    volumes:
      - "./server:/app"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: prod.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - reservas_network
    # depends_on:
    #   - server

networks:
  reservas_network:
    external: true
