version: "3"

services:
  server:
    container_name: server
    hostname: server
    build:
      context: ./server
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: rHI0GQaOBbGpgKIlWPoIEg==,rHISyIBBaL+b5xSer+IMig==,sDZCAQ5zP+Z76GlazrjJpg==,arbUlg8oMIDHis7yDg3fXQ==
      API_TOKEN_SALT: pkzp8CbAKjx1mAXgxkmxvA==
      ADMIN_JWT_SECRET: r+wVmbxrraQbir5qD2TOZQ==
      TRANSFER_TOKEN_SALT: 6UCJkVMvwvj2amU9MbCs3g==
      # Database
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: zBmcnlQzN/lxxwR03f8UnA==
    ports:
      - "1337:1337"
    volumes:
      - "./server:/app"
    networks:
      - reservas_network
  client:
    container_name: client
    hostname: client
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://server:1337/api
      NEXTAUTH_SECRET: 5447a6d673eb747a479bc0bc00a93651
      NEXTAUTH_URL: http://localhost:3000/api/auth
    volumes:
      - "./client:/app"
      - "./client/src:/app/src"
      - ./client/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - reservas_network
    depends_on:
      - server

networks:
  reservas_network:
    driver: bridge
    # external: false
    # name: reservas_network
